# Generated by Django 5.0.6 on 2024-07-19 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0002_alter_profile_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name_plural': 'Profiles'},
        ),
    ]
